//! Renders generation headers and identifies the generator named by a header.
//!
//! This layer handles only header text and nodes. It does not read or write
//! files, decide whether an existing file may be replaced, or build document
//! bodies from the topic model.

use std::path::Path;

use rd_ast::RdNode;
use unicode_width::UnicodeWidthStr;

const GENERATED_PREFIX: &str = " Generated by ";
const GENERATED_SUFFIX: &str = ": do not edit by hand";
pub const GENERATOR_NAME: &str = "mini-roxygen (roxygen2 compatible)";
const HEADER_WIDTH: usize = 80;
const SOURCE_FILES_LEAD: &str = "Please edit documentation in ";
const RD_COMMENT: char = '%';
const NAMESPACE_COMMENT: char = '#';
const INITIAL_PREFIX: &str = "% ";
const CONTINUATION_PREFIX: &str = "%   ";

/// Identifies the generator named by a generation marker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Generator {
    /// This generator, identified by GENERATOR_NAME.
    MiniRoxygen,
    /// The generator used by roxygen2.
    Roxygen2,
    /// A valid marker naming another generator.
    Other(String),
}

/// Classifies the content of a file using its leading generation marker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileClassification {
    /// The file is marked as generated by the contained generator.
    Generated(Generator),
    /// The file does not have a valid generation marker on its first line.
    HandWritten,
}

/// Classifies file content by its first line.
///
/// A marker has one leading comment character, the fixed marker text, a
/// non-empty generator name, and the fixed suffix. The leading character is
/// intentionally not restricted so that Rd and NAMESPACE markers share the
/// same detection rule.
pub fn classify(content: &str) -> FileClassification {
    let first_line = content
        .split_once('\n')
        .map_or(content, |(line, _)| line.strip_suffix('\r').unwrap_or(line));
    let mut characters = first_line.chars();
    let Some(_) = characters.next() else {
        return FileClassification::HandWritten;
    };
    let marker = characters.as_str();
    let Some(marker) = marker.strip_prefix(GENERATED_PREFIX) else {
        return FileClassification::HandWritten;
    };
    let marker = marker.strip_suffix(GENERATED_SUFFIX).unwrap_or("");
    if marker.is_empty() || marker.contains([':', '\r', '\n']) {
        return FileClassification::HandWritten;
    }

    let generator = if marker == GENERATOR_NAME {
        Generator::MiniRoxygen
    } else if marker == "roxygen2" {
        Generator::Roxygen2
    } else {
        Generator::Other(marker.to_owned())
    };
    FileClassification::Generated(generator)
}

/// Reduces a source path to its final two components joined by slash.
///
/// A one-component path keeps that component. An empty path has no components
/// and therefore reduces to an empty string. The returned separator is always
/// slash; path components themselves use the platform's normal path rules.
pub fn reduce_source_path(path: impl AsRef<Path>) -> String {
    let components: Vec<String> = path
        .as_ref()
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect();
    let start = components.len().saturating_sub(2);
    components[start..].join("/")
}

/// Renders the source-file comment block for a collection of source paths.
///
/// Paths are deduplicated in first-seen order before reduction. The returned
/// strings do not contain newline characters. An empty collection returns no
/// lines.
pub fn render_source_file_block<I, P>(paths: I) -> Vec<String>
where
    I: IntoIterator<Item = P>,
    P: AsRef<Path>,
{
    let mut unique_paths = Vec::new();
    for path in paths {
        let path = path.as_ref();
        if !unique_paths.iter().any(|seen| seen == path) {
            unique_paths.push(path.to_owned());
        }
    }
    if unique_paths.is_empty() {
        return Vec::new();
    }

    let text = format!(
        "{SOURCE_FILES_LEAD}{}",
        unique_paths
            .iter()
            .map(reduce_source_path)
            .collect::<Vec<_>>()
            .join(", ")
    );
    wrap_text(&text)
}

/// Renders the complete Rd generation header as writer-valid nodes.
pub fn render_rd_header<I, P>(paths: I) -> Vec<RdNode>
where
    I: IntoIterator<Item = P>,
    P: AsRef<Path>,
{
    let paths = paths
        .into_iter()
        .map(|path| path.as_ref().to_owned())
        .collect::<Vec<_>>();
    let source_lines = render_source_file_block(&paths);
    let mut nodes = Vec::new();
    for line in std::iter::once(generated_marker(RD_COMMENT)).chain(source_lines.iter().cloned()) {
        nodes.push(RdNode::Comment(line));
        nodes.push(RdNode::Text("\n".to_owned()));
    }
    nodes
}

/// Renders the NAMESPACE generation header, including the blank line that
/// separates it from the first directive.
///
/// The Rd header has no such blank line: there the marker is followed
/// immediately by the source-file line.
pub fn render_namespace_header() -> String {
    format!("{}\n\n", generated_marker(NAMESPACE_COMMENT))
}

fn generated_marker(comment: char) -> String {
    format!("{comment}{GENERATED_PREFIX}{GENERATOR_NAME}{GENERATED_SUFFIX}")
}

fn wrap_text(text: &str) -> Vec<String> {
    let words: Vec<&str> = text.split_whitespace().collect();
    let mut lines = Vec::new();
    let mut current = String::new();
    let mut prefix = INITIAL_PREFIX;

    for word in words {
        // A line breaks once it would reach the target column, so a wrapped
        // line stays strictly below it. Only a word that cannot fit a line of
        // its own overruns the column. Columns are display width, not scalar
        // count: R measures the same way, so a wide or combining character
        // moves the break.
        let available = HEADER_WIDTH.saturating_sub(prefix.width());
        let fits = !current.is_empty() && current.width() + 1 + word.width() < available;
        if fits {
            current.push(' ');
            current.push_str(word);
        } else {
            if !current.is_empty() {
                lines.push(format!("{prefix}{current}"));
                prefix = CONTINUATION_PREFIX;
                current.clear();
            }
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(format!("{prefix}{current}"));
    }
    lines
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use rd_ast::{RdDocument, RdNode};
    use rd_writer::Writer;
    use unicode_width::UnicodeWidthStr;

    use super::{
        CONTINUATION_PREFIX, FileClassification, GENERATOR_NAME, Generator, HEADER_WIDTH,
        INITIAL_PREFIX, classify, reduce_source_path, render_namespace_header, render_rd_header,
        render_source_file_block,
    };
    use crate::rd_oracle::assert_r_strwrap_matches;

    #[test]
    fn classification_recognizes_supported_markers_and_rejects_near_misses() {
        assert_eq!(
            classify(&format!(
                "% Generated by {GENERATOR_NAME}: do not edit by hand\n"
            )),
            FileClassification::Generated(Generator::MiniRoxygen)
        );
        assert_eq!(
            classify(&format!(
                "# Generated by {GENERATOR_NAME}: do not edit by hand\r\n"
            )),
            FileClassification::Generated(Generator::MiniRoxygen)
        );
        assert_eq!(
            classify("% Generated by roxygen2: do not edit by hand\n"),
            FileClassification::Generated(Generator::Roxygen2)
        );
        assert_eq!(
            classify("# Generated by roxygen2: do not edit by hand\n"),
            FileClassification::Generated(Generator::Roxygen2)
        );
        assert_eq!(
            classify("# Generated by cpp11: do not edit by hand\n"),
            FileClassification::Generated(Generator::Other("cpp11".to_owned()))
        );
        assert_eq!(
            classify("% Generated by roxygen2-compatible: do not edit by hand\n"),
            FileClassification::Generated(Generator::Other("roxygen2-compatible".to_owned(),))
        );
        assert_eq!(
            classify("% Generated by mini-roxygen: do not edit by hand\n"),
            FileClassification::Generated(Generator::Other("mini-roxygen".to_owned()))
        );
        let contents = vec![
            "# hand-written\n".to_owned(),
            String::new(),
            format!("% Generated by {GENERATOR_NAME}: do not edit\n"),
            "% Generated by : do not edit by hand\n".to_owned(),
            "% Generated by a:b: do not edit by hand\n".to_owned(),
            "% Generated by cpp11\r: do not edit by hand\n".to_owned(),
            format!("% Generated by {GENERATOR_NAME}: do not edit by hand\r"),
            format!("body\n% Generated by {GENERATOR_NAME}: do not edit by hand\n"),
        ];
        for content in contents {
            assert_eq!(
                classify(&content),
                FileClassification::HandWritten,
                "{content:?}"
            );
        }
    }

    #[test]
    fn source_paths_keep_the_last_two_components() {
        assert_eq!(
            reduce_source_path(Path::new("src/R/example.R")),
            "R/example.R"
        );
        assert_eq!(reduce_source_path(Path::new("R/example.R")), "R/example.R");
        assert_eq!(reduce_source_path(Path::new("example.R")), "example.R");
        assert_eq!(reduce_source_path(Path::new("")), "");
    }

    #[test]
    fn source_file_blocks_wrap_deduplicate_and_preserve_order() {
        assert!(render_source_file_block(Vec::<PathBuf>::new()).is_empty());
        assert_eq!(
            render_source_file_block([Path::new("src/R/example.R")]),
            vec!["% Please edit documentation in R/example.R"]
        );
        assert_eq!(
            render_source_file_block([Path::new("src/R/first.R"), Path::new("src/R/second.R"),]),
            vec!["% Please edit documentation in R/first.R, R/second.R"]
        );

        let wrapped = render_source_file_block([
            Path::new("R/one-with-a-long-name.R"),
            Path::new("R/two-with-a-long-name.R"),
            Path::new("R/three-with-a-long-name.R"),
            Path::new("R/four-with-a-long-name.R"),
        ]);
        assert!(wrapped.len() > 1);
        assert!(
            wrapped[1..]
                .iter()
                .all(|line| line.starts_with(CONTINUATION_PREFIX))
        );
        assert!(wrapped.iter().all(|line| line.width() < HEADER_WIDTH));

        assert_eq!(
            render_source_file_block([
                Path::new("R/first.R"),
                Path::new("R/first.R"),
                Path::new("src/R/second.R"),
            ]),
            vec!["% Please edit documentation in R/first.R, R/second.R"]
        );
    }

    #[test]
    fn rd_and_namespace_headers_render_expected_text_and_nodes() {
        let paths = [Path::new("src/R/example.R"), Path::new("src/R/another.R")];
        let nodes = render_rd_header(paths);
        assert_eq!(
            nodes,
            vec![
                RdNode::Comment(format!(
                    "% Generated by {GENERATOR_NAME}: do not edit by hand"
                ),),
                RdNode::Text("\n".to_owned()),
                RdNode::Comment(
                    "% Please edit documentation in R/example.R, R/another.R".to_owned(),
                ),
                RdNode::Text("\n".to_owned()),
            ]
        );
        let text = Writer::new(rd_writer::WriterOptions::default())
            .write_document(&RdDocument::from(nodes.clone()))
            .expect("generation header must satisfy rd-writer");
        assert_eq!(
            text,
            format!(
                "% Generated by {GENERATOR_NAME}: do not edit by hand\n% Please edit documentation in R/example.R, R/another.R\n"
            )
        );
        // The NAMESPACE header is followed by a blank line; the Rd header
        // asserted above is not, because its next line names the source file.
        assert_eq!(
            render_namespace_header(),
            format!("# Generated by {GENERATOR_NAME}: do not edit by hand\n\n")
        );
        assert_eq!(
            classify(&text),
            FileClassification::Generated(Generator::MiniRoxygen)
        );

        let document = RdDocument::from(nodes);
        let header = document.generation_header().unwrap();
        assert_eq!(
            header.generator(),
            Some(&rd_ast::RdGenerator::Unknown(GENERATOR_NAME.to_owned()))
        );
        assert_eq!(header.source_files(), &["R/example.R", "R/another.R"]);
    }

    #[test]
    fn rd_header_is_marker_only_without_source_paths() {
        let nodes = render_rd_header(std::iter::empty::<&Path>());
        assert_eq!(
            nodes,
            vec![
                RdNode::Comment(format!(
                    "% Generated by {GENERATOR_NAME}: do not edit by hand"
                )),
                RdNode::Text("\n".to_owned()),
            ]
        );
    }

    /// Builds a two-word text whose unwrapped line would occupy `columns`.
    ///
    /// The first word is short enough to leave the join decision to the second,
    /// so sweeping `columns` across the target column walks the boundary where
    /// a word stops fitting beside its predecessor.
    fn join_case(prefix_width: usize, lead: &str, columns: usize) -> String {
        let tail = columns - prefix_width - lead.width() - 1;
        format!("{lead} {}", "b".repeat(tail))
    }

    #[test]
    fn wrapping_matches_r_at_boundaries_and_for_long_lists() {
        let mut cases = vec![
            format!("Please edit documentation in {}", "a".repeat(60)),
            format!("Please edit documentation in {}", "a".repeat(61)),
            format!("Please edit documentation in {}", "a".repeat(100)),
            format!(
                "Please edit documentation in {}",
                (1..=36)
                    .map(|index| format!("R/file-{index:02}.R"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        ];
        // Walk the column at which a word stops fitting beside its predecessor,
        // on the first line and again on a continuation line. A single long
        // word never reaches that decision, so the cases above cannot pin it.
        for columns in 76..=84 {
            cases.push(join_case(INITIAL_PREFIX.width(), "aa", columns));
            cases.push(format!(
                "{} {}",
                "h".repeat(76),
                join_case(CONTINUATION_PREFIX.width(), "aa", columns)
            ));
        }
        // A column is a display column, so a wide character advances it twice
        // and a combining mark not at all. Walk the same boundary with each,
        // since a scalar count agrees with a display width only for the
        // narrow characters the cases above use.
        for wide in 36..=40 {
            cases.push(format!(
                "Please edit documentation in R/{}.R",
                "あ".repeat(wide)
            ));
            // Width 5 + 2 * wide unwrapped, so this sweeps the same boundary.
            cases.push(format!("aa {}", "あ".repeat(wide)));
        }
        // A combining mark costs a column only under a scalar count, so the
        // sweep has to sit where the two disagree about the break: the word is
        // `combining + 4` columns wide but twice that many scalars, and the
        // first line has 78 columns left after its lead.
        for combining in 42..=46 {
            cases.push(format!(
                "Please edit documentation in R/{}.R",
                "e\u{0301}".repeat(combining)
            ));
        }
        let expected = cases
            .iter()
            .map(|case| super::wrap_text(case))
            .collect::<Vec<_>>();
        assert_r_strwrap_matches(&cases, &expected);
    }
}
