//! Core parsing, intermediate representation, inheritance, and output building for mini-roxygen.
//!
//! The library is organized as a one-way pipeline from source files through
//! static analysis and tag interpretation to Rd and NAMESPACE output.
//!
//! A complete documentation run starts with package metadata and source files,
//! then returns both generated artifacts and structured diagnostics:
//!
//! ```
//! use mini_roxygen_core::{PackageInputs, PackageMetadata, SourceMap, document_package};
//!
//! let inputs = PackageInputs {
//!     sources: SourceMap::new(),
//!     metadata: PackageMetadata::new("example", None).expect("valid package metadata"),
//! };
//! let output = document_package(&inputs);
//!
//! assert!(!output.has_errors());
//! assert!(output.rd.files.is_empty());
//! assert!(output.namespace.content.contains("Generated by mini-roxygen"));
//! ```

mod arity_adapter;
mod diagnostic;
mod generation;
mod inherit;
mod inline_r;
pub(crate) mod marc_roles;
mod markdown;
pub(crate) mod markdown_conversion;
mod model;
mod namespace;
mod package;
mod pipeline;
mod r_parse;
pub(crate) mod r_syntax;
mod rd;
#[cfg(test)]
mod rd_oracle;
mod s3_register;
mod source;
mod tags;
mod usage;

pub use diagnostic::{Diagnostic, DiagnosticCode, Diagnostics, Label, Severity};
pub use generation::{FileClassification, Generator, classify};
pub use inherit::{
    DocumentationError, DocumentationErrorKind, DocumentationIdentity, DocumentationOrigin,
    DocumentationProvider, ExternalInheritancePolicy, ExternalPolicySource, InheritableContent,
    InheritableFields, InheritableParamGroup, InheritableParamLabel, InheritableSection,
    InheritableTopic, InheritanceOptions, InheritanceTrace, ResolvedContent, TopicExistence,
    TopicRequest, project_external_topic,
};
pub use inline_r::InlineRSubstitutions;
pub use model::TopicKey;
pub use namespace::{EmptyS3GenericProvider, NamespaceBuildOutput, S3GenericProvider};
pub use package::{
    PackageDocumentationMetadata, PackageInputError, PackageInputs, PackageMetadata,
    PackageMetadataError,
};
pub use pipeline::{
    DocumentOptions, PackageOutput, document_package, document_package_with_options,
    document_package_with_options_and_providers, document_package_with_options_and_s3_provider,
};
pub use rd::{GeneratedRd, RdBuildOutput};
pub use s3_register::{S3RegistrarRole, S3RegistrarSet, S3RegistrarSignature};
pub use source::{FileId, SourceError, SourceFile, SourceMap, Span, Spanned, TextRange};
pub use tags::{
    ArgSelection, ArgSelector, ExamplesContent, ExamplesIf, InheritField, InheritFields,
    InheritTarget, MarkdownText, ParamName, RCodeText, SourcedText, TagOrigin, TopicRef,
};
