//! The 302-code MARC relator subset accepted by R's `person()` role path.
//!
//! The historical source table was generated from R's
//! `utils::MARC_relator_db`. The current table was rederived and independently
//! checked against the Library of Congress public-domain Linked Data Service
//! relator vocabulary on 2026-08-14; see `THIRD_PARTY_NOTICES.md` for the
//! source URL and provenance notes. Three LC codes that R 4.6.1 warns
//! for are excluded to preserve the accepted-code compatibility subset. Sorted
//! by code so lookups can binary-search.
//!
//! R's `utils` package is licensed under GPL-2 or GPL-3, and the maintained
//! public-domain LC vocabulary is published at
//! <https://id.loc.gov/vocabulary/relators.json>.

/// Maps a MARC relator code to its Library of Congress term for the
/// R-recognized compatibility subset.
const ROLE_TERMS: &[(&str, &str)] = &[
    ("abr", "abridger"),
    ("acp", "art copyist"),
    ("act", "actor"),
    ("adi", "art director"),
    ("adp", "adapter"),
    ("aft", "author of afterword, colophon, etc."),
    ("anc", "announcer"),
    ("anl", "analyst"),
    ("anm", "animator"),
    ("ann", "annotator"),
    ("ant", "bibliographic antecedent"),
    ("ape", "appellee"),
    ("apl", "appellant"),
    ("app", "applicant"),
    ("aqt", "author in quotations or text abstracts"),
    ("arc", "architect"),
    ("ard", "artistic director"),
    ("arr", "arranger"),
    ("art", "artist"),
    ("asg", "assignee"),
    ("asn", "associated name"),
    ("ato", "autographer"),
    ("att", "attributed name"),
    ("auc", "auctioneer"),
    ("aud", "author of dialog"),
    ("aue", "audio engineer"),
    ("aui", "author of introduction, etc."),
    ("aup", "audio producer"),
    ("aus", "screenwriter"),
    ("aut", "author"),
    ("bdd", "binding designer"),
    ("bjd", "bookjacket designer"),
    ("bka", "book artist"),
    ("bkd", "book designer"),
    ("bkp", "book producer"),
    ("blw", "blurb writer"),
    ("bnd", "binder"),
    ("bpd", "bookplate designer"),
    ("brd", "broadcaster"),
    ("brl", "braille embosser"),
    ("bsl", "bookseller"),
    ("cad", "casting director"),
    ("cas", "caster"),
    ("ccp", "conceptor"),
    ("chr", "choreographer"),
    ("cli", "client"),
    ("cll", "calligrapher"),
    ("clr", "colorist"),
    ("clt", "collotyper"),
    ("cmm", "commentator"),
    ("cmp", "composer"),
    ("cmt", "compositor"),
    ("cnd", "conductor"),
    ("cng", "cinematographer"),
    ("cns", "censor"),
    ("coe", "contestant-appellee"),
    ("col", "collector"),
    ("com", "compiler"),
    ("con", "conservator"),
    ("cop", "camera operator"),
    ("cor", "collection registrar"),
    ("cos", "contestant"),
    ("cot", "contestant-appellant"),
    ("cou", "court governed"),
    ("cov", "cover designer"),
    ("cpc", "copyright claimant"),
    ("cpe", "complainant-appellee"),
    ("cph", "copyright holder"),
    ("cpl", "complainant"),
    ("cpt", "complainant-appellant"),
    ("cre", "creator"),
    ("crp", "correspondent"),
    ("crr", "corrector"),
    ("crt", "court reporter"),
    ("csl", "consultant"),
    ("csp", "consultant to a project"),
    ("cst", "costume designer"),
    ("ctb", "contributor"),
    ("cte", "contestee-appellee"),
    ("ctg", "cartographer"),
    ("ctr", "contractor"),
    ("cts", "contestee"),
    ("ctt", "contestee-appellant"),
    ("cur", "curator"),
    ("cwt", "commentator for written text"),
    ("dbd", "dubbing director"),
    ("dbp", "distribution place"),
    ("dfd", "defendant"),
    ("dfe", "defendant-appellee"),
    ("dft", "defendant-appellant"),
    ("dgc", "degree committee member"),
    ("dgg", "degree granting institution"),
    ("dgs", "degree supervisor"),
    ("dis", "dissertant"),
    ("djo", "dj"),
    ("dln", "delineator"),
    ("dnc", "dancer"),
    ("dnr", "donor"),
    ("dpc", "depicted"),
    ("dpt", "depositor"),
    ("drm", "draftsman"),
    ("drt", "director"),
    ("dsr", "designer"),
    ("dst", "distributor"),
    ("dtc", "data contributor"),
    ("dte", "dedicatee"),
    ("dtm", "data manager"),
    ("dto", "dedicator"),
    ("dub", "dubious author"),
    ("edc", "editor of compilation"),
    ("edd", "editorial director"),
    ("edm", "editor of moving image work"),
    ("edt", "editor"),
    ("egr", "engraver"),
    ("elg", "electrician"),
    ("elt", "electrotyper"),
    ("eng", "engineer"),
    ("enj", "enacting jurisdiction"),
    ("etr", "etcher"),
    ("evp", "event place"),
    ("exp", "expert"),
    ("fac", "facsimilist"),
    ("fds", "film distributor"),
    ("fld", "field director"),
    ("flm", "film editor"),
    ("fmd", "film director"),
    ("fmk", "filmmaker"),
    ("fmo", "former owner"),
    ("fmp", "film producer"),
    ("fnd", "funder"),
    ("fon", "founder"),
    ("fpy", "first party"),
    ("frg", "forger"),
    ("gdv", "game developer"),
    ("gis", "geographic information specialist"),
    ("his", "host institution"),
    ("hnr", "honoree"),
    ("hst", "host"),
    ("ill", "illustrator"),
    ("ilu", "illuminator"),
    ("ink", "inker"),
    ("ins", "inscriber"),
    ("inv", "inventor"),
    ("isb", "issuing body"),
    ("itr", "instrumentalist"),
    ("ive", "interviewee"),
    ("ivr", "interviewer"),
    ("jud", "judge"),
    ("jug", "jurisdiction governed"),
    ("lbr", "laboratory"),
    ("lbt", "librettist"),
    ("ldr", "laboratory director"),
    ("led", "lead"),
    ("lee", "libelee-appellee"),
    ("lel", "libelee"),
    ("len", "lender"),
    ("let", "libelee-appellant"),
    ("lgd", "lighting designer"),
    ("lie", "libelant-appellee"),
    ("lil", "libelant"),
    ("lit", "libelant-appellant"),
    ("lsa", "landscape architect"),
    ("lse", "licensee"),
    ("lso", "licensor"),
    ("ltg", "lithographer"),
    ("ltr", "letterer"),
    ("lyr", "lyricist"),
    ("mcp", "music copyist"),
    ("mdc", "metadata contact"),
    ("med", "medium"),
    ("mfp", "manufacture place"),
    ("mfr", "manufacturer"),
    ("mka", "makeup artist"),
    ("mod", "moderator"),
    ("mon", "monitor"),
    ("mrb", "marbler"),
    ("mrk", "markup editor"),
    ("msd", "musical director"),
    ("mte", "metal engraver"),
    ("mtk", "minute taker"),
    ("mup", "music programmer"),
    ("mus", "musician"),
    ("mxe", "mixing engineer"),
    ("nan", "news anchor"),
    ("nrt", "narrator"),
    ("onp", "onscreen participant"),
    ("opn", "opponent"),
    ("org", "originator"),
    ("orm", "organizer"),
    ("osp", "onscreen presenter"),
    ("oth", "other"),
    ("own", "owner"),
    ("pad", "place of address"),
    ("pan", "panelist"),
    ("pat", "patron"),
    ("pbd", "publisher director"),
    ("pbl", "publisher"),
    ("pdr", "project director"),
    ("pfr", "proofreader"),
    ("pht", "photographer"),
    ("plt", "platemaker"),
    ("pma", "permitting agency"),
    ("pmn", "production manager"),
    ("pnc", "penciller"),
    ("pop", "printer of plates"),
    ("ppm", "papermaker"),
    ("ppt", "puppeteer"),
    ("pra", "praeses"),
    ("prc", "process contact"),
    ("prd", "production personnel"),
    ("pre", "presenter"),
    ("prf", "performer"),
    ("prg", "programmer"),
    ("prm", "printmaker"),
    ("prn", "production company"),
    ("pro", "producer"),
    ("prp", "production place"),
    ("prs", "production designer"),
    ("prt", "printer"),
    ("prv", "provider"),
    ("pta", "patent applicant"),
    ("pte", "plaintiff-appellee"),
    ("ptf", "plaintiff"),
    ("pth", "patent holder"),
    ("ptt", "plaintiff-appellant"),
    ("pup", "publication place"),
    ("rap", "rapporteur"),
    ("rbr", "rubricator"),
    ("rcd", "recordist"),
    ("rce", "recording engineer"),
    ("rcp", "addressee"),
    ("rdd", "radio director"),
    ("red", "redaktor"),
    ("ren", "renderer"),
    ("res", "researcher"),
    ("rev", "reviewer"),
    ("rpc", "radio producer"),
    ("rps", "repository"),
    ("rpt", "reporter"),
    ("rpy", "responsible party"),
    ("rse", "respondent-appellee"),
    ("rsg", "restager"),
    ("rsp", "respondent"),
    ("rsr", "restorationist"),
    ("rst", "respondent-appellant"),
    ("rth", "research team head"),
    ("rtm", "research team member"),
    ("rxa", "remix artist"),
    ("sad", "scientific advisor"),
    ("sce", "scenarist"),
    ("scl", "sculptor"),
    ("scr", "scribe"),
    ("sde", "sound engineer"),
    ("sds", "sound designer"),
    ("sec", "secretary"),
    ("sfx", "special effects provider"),
    ("sgd", "stage director"),
    ("sgn", "signer"),
    ("sht", "supporting host"),
    ("sll", "seller"),
    ("sng", "singer"),
    ("spk", "speaker"),
    ("spn", "sponsor"),
    ("spy", "second party"),
    ("srv", "surveyor"),
    ("std", "set designer"),
    ("stg", "setting"),
    ("stl", "storyteller"),
    ("stm", "stage manager"),
    ("stn", "standards body"),
    ("str", "stereotyper"),
    ("swd", "software developer"),
    ("tad", "technical advisor"),
    ("tau", "television writer"),
    ("tcd", "technical director"),
    ("tch", "teacher"),
    ("ths", "thesis advisor"),
    ("tld", "television director"),
    ("tlg", "television guest"),
    ("tlh", "television host"),
    ("tlp", "television producer"),
    ("trc", "transcriber"),
    ("trl", "translator"),
    ("tyd", "type designer"),
    ("tyg", "typographer"),
    ("uvp", "university place"),
    ("vac", "voice actor"),
    ("vdg", "videographer"),
    ("vfx", "visual effects provider"),
    ("wac", "writer of added commentary"),
    ("wal", "writer of added lyrics"),
    ("wam", "writer of accompanying material"),
    ("wat", "writer of added text"),
    ("wdc", "woodcutter"),
    ("wde", "wood engraver"),
    ("wfs", "writer of film story"),
    ("wft", "writer of intertitles"),
    ("win", "writer of introduction"),
    ("wit", "witness"),
    ("wpr", "writer of preface"),
    ("wst", "writer of supplementary textual content"),
    ("wts", "writer of television story"),
];

/// Returns the Library of Congress label for a code in the R-recognized
/// compatibility subset.
pub(crate) fn role_term(code: &str) -> Option<&'static str> {
    ROLE_TERMS
        .binary_search_by(|(known, _)| (*known).cmp(code))
        .ok()
        .map(|index| ROLE_TERMS[index].1)
}

#[cfg(test)]
mod tests {
    use super::{ROLE_TERMS, role_term};

    #[test]
    fn the_table_is_sorted_and_unique_so_binary_search_is_valid() {
        assert!(ROLE_TERMS.windows(2).all(|pair| pair[0].0 < pair[1].0));
        assert_eq!(ROLE_TERMS.len(), 302);
    }

    #[test]
    fn known_codes_resolve_and_unknown_ones_do_not() {
        assert_eq!(role_term("cph"), Some("copyright holder"));
        assert_eq!(role_term("fnd"), Some("funder"));
        assert_eq!(role_term("ctb"), Some("contributor"));
        assert_eq!(role_term("aut"), Some("author"));
        assert_eq!(role_term("cre"), Some("creator"));
        assert_eq!(role_term("mte"), Some("metal engraver"));
        assert_eq!(role_term("pbd"), Some("publisher director"));
        assert_eq!(role_term("zzz"), None);
        assert_eq!(role_term(""), None);
    }
}
