use std::collections::BTreeSet;

use super::render::quote_name;
use super::{
    S3GenericProvider, build_namespace, build_namespace_with_provider, build_namespace_with_sources,
};
use crate::diagnostic::{DiagnosticCode, Severity};
use crate::model::test_support::model;
use crate::model::{
    BlockRef, DocumentedBlock, build_package_model_with_bindings,
    build_package_model_with_metadata_and_bindings,
};
use crate::package::PackageMetadata;
use crate::r_parse::build_object_index;
use crate::source::{SourceFile, SourceMap, TextRange};
use crate::tags::{TagParseOptions, UnknownTagPolicy};

fn namespace(text: &str) -> super::NamespaceBuildOutput {
    namespace_with_package(text, None)
}

fn namespace_with_package(
    text: &str,
    current_package: Option<&str>,
) -> super::NamespaceBuildOutput {
    build_namespace(&model(text).package, current_package)
}

fn namespace_files(files: &[(&str, &str)]) -> super::NamespaceBuildOutput {
    namespace_files_with_collate(files, false)
}

fn namespace_files_with_collate(
    files: &[(&str, &str)],
    collate: bool,
) -> super::NamespaceBuildOutput {
    let (package, sources) = package_files_with_collate(files, collate);
    build_namespace_with_sources(&package, &sources, None)
}

fn package_files_with_collate(
    files: &[(&str, &str)],
    collate: bool,
) -> (crate::model::PackageModel, SourceMap) {
    let mut sources = SourceMap::new();
    let mut all_blocks = Vec::new();
    let mut all_bindings = Vec::new();
    for (path, text) in files {
        let source = SourceFile::new((*path).into(), (*text).to_owned());
        let file = sources.add_file(source.clone());
        let index = build_object_index(crate::arity_adapter::parse(&source, file), file);
        all_bindings.extend(index.bindings.iter().cloned());
        let parsed = crate::arity_adapter::parse(&source, file);
        for object in index.documented {
            let raw = parsed
                .top_level
                .iter()
                .find_map(|entry| {
                    entry
                        .documentation
                        .as_ref()
                        .filter(|block| block.id == object.block)
                })
                .expect("indexed object has documentation");
            let (tags, diagnostics) = crate::tags::parse_block(
                &source,
                raw,
                &TagParseOptions::default().with_unknown_tags(UnknownTagPolicy::Ignore),
            );
            assert!(diagnostics.is_empty());
            all_blocks.push(DocumentedBlock {
                block: BlockRef {
                    file,
                    block: object.block,
                },
                block_span: object.block_span,
                target: object.target,
                tags,
            });
        }
    }
    let package = if collate {
        let metadata = PackageMetadata::new("example", None)
            .expect("valid package metadata")
            .with_collate_directive();
        build_package_model_with_metadata_and_bindings(
            &sources,
            all_blocks,
            &metadata,
            all_bindings,
        )
        .package
    } else {
        build_package_model_with_bindings(&sources, all_blocks, all_bindings).package
    };
    (package, sources)
}

#[test]
fn export_uses_the_implicit_function_assignment_name() {
    let output = namespace(
        r#"#' @export
add <- function(x) x
        "#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(add)
    ");
}

#[test]
fn export_uses_an_explicit_name() {
    let output = namespace(
        r#"#' @export other
add <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(other)
    ");
}

#[test]
fn method_with_bare_export_registers_an_s3_method_instead_of_exporting_object() {
    let output = namespace(
        r#"#' @method print data.frame
#' @export
print.data.frame <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(print,data.frame)
    ");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn provider_classifies_ordinary_and_operator_methods() {
    let source = r#"#' @export
print.foo <- function(x) x
#' @export
`+.foo` <- function(x, y) x
#' @export
`$.foo` <- function(x, name) x[[name]]
"#;
    let model = model(source);
    let provider = FakeGenericProvider(BTreeSet::from([
        "print".to_owned(),
        "+".to_owned(),
        "$".to_owned(),
    ]));
    let output = build_namespace_with_provider(&model.package, None, &provider);
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method("$",foo)
S3method("+",foo)
S3method(print,foo)
"#);
    assert!(output.diagnostics.is_empty());
}

struct FakeGenericProvider(BTreeSet<String>);

impl S3GenericProvider for FakeGenericProvider {
    fn is_s3_generic(&self, name: &str) -> bool {
        self.0.contains(name)
    }
}

#[test]
fn local_bindings_shadow_provider_facts_conservatively() {
    let source = r#"print <- 1
#' @export
print.foo <- function(x) x
summary <- function(x) x
#' @export
summary.foo <- function(x) x
mean <- missing
#' @export
mean.foo <- function(x) x
max <- function(x) x
max <- function(x) x
#' @export
max.foo <- function(x) x
"#;
    let model = model(source);
    let provider = FakeGenericProvider(BTreeSet::from([
        "print".to_owned(),
        "summary".to_owned(),
        "mean".to_owned(),
        "max".to_owned(),
    ]));
    let output = build_namespace_with_provider(&model.package, None, &provider);
    insta::assert_snapshot!(output.content, @"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    ");
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        4
    );
}

#[test]
fn local_use_method_fact_remains_authoritative_for_builtin_name() {
    let output = namespace(
        r#"print <- function(x) UseMethod("print")
#' @export
print.foo <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(print,foo)
    ");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn method_arguments_use_automatic_quoting_for_non_syntactic_names() {
    let output = namespace(
        r#"#' @method $ fixture::FixtureExpr
#' @export
`$.fixture::FixtureExpr` <- function(x, name) NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method("$","fixture::FixtureExpr")
    "#);
    assert!(output.diagnostics.is_empty());
}

#[test]
fn already_quoted_method_arguments_are_not_quoted_again() {
    let output = namespace(
        r#"#' @method '$' 'fixture::FixtureExpr'
#' @export
`$.fixture::FixtureExpr` <- function(x, name) NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method("$","fixture::FixtureExpr")
    "#);
    assert!(output.diagnostics.is_empty());
}

#[test]
fn syntactic_method_arguments_are_not_quoted() {
    let output = namespace(
        r#"#' @method generic class
#' @export
method.class <- function() NULL
"#,
    );
    assert!(output.content.ends_with("S3method(generic,class)\n"));
    assert!(!output.content.contains("S3method(\"generic\",\"class\")"));
    assert!(output.diagnostics.is_empty());
}

#[test]
fn explicit_export_name_does_not_take_the_method_s3_branch() {
    let output = namespace(
        r#"#' @method generic class
#' @export foo
method.class <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(foo)
    ");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn method_without_export_emits_no_namespace_directive() {
    let output = namespace(
        r#"#' @method generic class
method.class <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
    assert!(output.diagnostics.is_empty());
}

#[test]
fn method_export_on_a_non_function_is_rejected_without_s3_output() {
    let output = namespace(
        r#"#' @method generic class
#' @export
method.class <- 1
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        1
    );
}

#[test]
fn duplicate_method_exports_deduplicate_and_keep_namespace_ordering() {
    let output = namespace(
        r#"#' @import imported
NULL
#' @method generic class
#' @export
first.class <- function() NULL
#' @method generic class
#' @export
second.class <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(generic,class)
    import(imported)
    ");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn export_accepts_multiple_names_and_renders_each_word() {
    let output = namespace(
        r#"#' @export foo bar
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(bar)
    export(foo)
    ");
}

#[test]
fn explicit_s3_method_two_word_form_is_literal() {
    let output = namespace(
        r#"#' @exportS3Method print foo
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(print,foo)
    ");
}

#[test]
fn explicit_s3_method_two_word_form_does_not_quote_non_syntactic_arguments() {
    let output = namespace(
        r#"#' @exportS3Method foo-bar class/name
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(foo-bar,class/name)
    ");
}

#[test]
fn explicit_s3_method_one_word_form_derives_a_literal_class() {
    let output = namespace(
        r#"#' @exportS3Method utils::.DollarNames
`.DollarNames.fixture::RenderOptions` <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(utils::.DollarNames,fixture::RenderOptions)
    ");
}

#[test]
fn explicit_s3_method_one_word_form_rejects_a_mismatched_object_name() {
    let output = namespace(
        r#"#' @exportS3Method utils::.DollarNames
`other.fixture::RenderOptions` <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        1
    );
}

#[test]
fn explicit_s3_method_one_word_form_rejects_a_non_function_object() {
    let output = namespace(
        r#"#' @exportS3Method utils::.DollarNames
`.DollarNames.fixture::RenderOptions` <- 1
"#,
    );
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n"
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        1
    );
}

#[test]
fn malformed_explicit_s3_method_forms_are_rejected_without_output() {
    let output = namespace(
        r#"#' @exportS3Method one two three
NULL
"#,
    );
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n"
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        1
    );
}

#[test]
fn the_null_s3_method_form_emits_nothing_and_says_nothing() {
    // A method registered at load time, by an s3_register() call in .onLoad,
    // must not appear in NAMESPACE. Emitting nothing is the whole behaviour;
    // a diagnostic here would reject documentation that is already correct.
    let output = namespace(
        r#"#' @exportS3Method NULL
f <- function() NULL
"#,
    );
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n"
    );
    assert!(output.diagnostics.is_empty());
}

#[test]
fn the_null_s3_method_form_does_not_depend_on_recognizing_the_object() {
    // The tag says "no directive" on its own. A method built at run time has
    // no statically recognizable function assignment, and that is exactly the
    // case load-time registration exists for, so it must not be rejected.
    for source in [
        "#' @exportS3Method NULL\nmake_method()\n",
        "#' @exportS3Method NULL\nNULL\n",
        "#' @exportS3Method NULL\nnot_a_function <- 1\n",
    ] {
        let output = namespace(source);
        assert_eq!(
            output.content,
            "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n",
            "unexpected content for {source:?}"
        );
        assert!(
            output.diagnostics.is_empty(),
            "unexpected diagnostics for {source:?}"
        );
    }
}

#[test]
fn identical_s3_lines_from_different_quoting_routes_collapse_to_one() {
    // The auto-quoted and literal routes are kept apart so each renders the
    // way its originating tag demands, but two directives that render the
    // same text are the same registration. Deduplicating on the route instead
    // of the rendered spelling emitted the line twice.
    let output = namespace(
        r#"#' @method print foo
#' @export
print.foo <- function(x, ...) x
#' @exportS3Method print foo
NULL
"#,
    );
    assert_eq!(output.content.matches("S3method(print,foo)").count(), 1);
}

#[test]
fn identical_s3_lines_from_comma_bearing_literals_collapse_to_one() {
    // A literal argument may contain a comma, so splitting the key across the
    // two arguments is not injective over the rendered line: `a,b` plus `c`
    // and `a` plus `b,c` both render S3method(a,b,c).
    let output = namespace(
        r#"#' @exportS3Method a,b c
NULL
#' @exportS3Method a b,c
NULL
"#,
    );
    assert_eq!(output.content.matches("S3method(a,b,c)").count(), 1);
}

#[test]
fn s3_method_text_sorts_before_existing_namespace_directives() {
    let output = namespace(
        r#"#' @exportS3Method print foo
NULL
#' @export exported
NULL
#' @import imported
NULL
#' @importFrom utils head
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    S3method(print,foo)
    export(exported)
    import(imported)
    importFrom(utils,head)
    ");
}

#[test]
fn s3_method_lines_keep_compatibility_bytes() {
    let output = namespace(
        r#"#' @exportS3Method alpha base_class
NULL
#' @exportS3Method alpha default
NULL
#' @exportS3Method beta fixture_class
NULL
#' @exportS3Method gamma fixture_class
NULL
#' @exportS3Method delta fixture_group
NULL
"#,
    );
    let rendered = output
        .content
        .split_once("\n\n")
        .expect("namespace header separator")
        .1;
    assert_eq!(
        rendered.as_bytes(),
        b"S3method(alpha,base_class)\n\
S3method(alpha,default)\n\
S3method(beta,fixture_class)\n\
S3method(delta,fixture_group)\n\
S3method(gamma,fixture_class)\n"
    );
}

#[test]
fn rendered_export_text_orders_quoted_name_before_bare_name() {
    let output = namespace(
        r#"#' @export a z-
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export("z-")
    export(a)
    "#);
}

#[test]
fn duplicate_explicit_exports_collapse_to_one_directive() {
    let output = namespace(
        r#"#' @export foo foo
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(foo)
    ");
}

#[test]
fn non_syntactic_operator_and_replacement_names_are_double_quoted() {
    assert_eq!(quote_name("foo-bar"), "\"foo-bar\"");
    assert_eq!(quote_name("%>%"), "\"%>%\"");
    assert_eq!(quote_name("foo<-"), "\"foo<-\"");
    assert_eq!(quote_name("λ"), "\"λ\"");
}

#[test]
fn a_reserved_word_is_quoted_although_it_is_spelled_like_a_name() {
    // R's parser reserves these, so an unquoted directive would make the
    // file unparseable even though nothing in the spelling looks unusual.
    assert_eq!(quote_name("if"), r#""if""#);
    assert_eq!(quote_name("function"), r#""function""#);
    assert_eq!(quote_name("TRUE"), r#""TRUE""#);
    assert_eq!(quote_name("NA_complex_"), r#""NA_complex_""#);
    assert_eq!(quote_name("NA_character_"), r#""NA_character_""#);
    assert_eq!(quote_name("iffy"), "iffy");

    let output = namespace(
        r#"#' @export if function TRUE NA_complex_
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export("NA_complex_")
    export("TRUE")
    export("function")
    export("if")
    "#);
}

#[test]
fn implicit_non_syntactic_operator_and_replacement_names_are_quoted() {
    for (source_name, rendered_name) in [
        ("foo-bar", "\"foo-bar\""),
        ("+", "\"+\""),
        ("foo<-", "\"foo<-\""),
    ] {
        let output = namespace(&format!(
            r#"#' @export
`{source_name}` <- function() NULL
"#
        ));
        assert!(
            output
                .content
                .contains(&format!("export({rendered_name})\n"))
        );
    }
}

#[test]
fn import_and_import_from_are_rendered() {
    let output = namespace(
        r#"#' @import rlang
NULL
#' @importFrom utils head tail
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(rlang)
    importFrom(utils,
      head,
      tail
    )
    ");
}

#[test]
fn import_from_with_one_name_uses_roxygen2_spacing() {
    let output = namespace(
        r#"#' @importFrom stats median
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(stats,median)
    ");
}

#[test]
fn import_from_with_three_names_uses_roxygen2_multiline_form() {
    let output = namespace(
        r#"#' @importFrom pkg first second third
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(pkg,
      first,
      second,
      third
    )
    ");
}

#[test]
fn import_accepts_multiple_packages() {
    let output = namespace(
        r#"#' @import stats utils
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(stats)
    import(utils)
    ");
}

#[test]
fn comma_bearing_import_is_emitted_verbatim() {
    let output = namespace(
        r#"#' @import rlang, except = ':='
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(rlang, except = ':=')
    ");
}

#[test]
fn rendered_import_text_interleaves_typed_and_verbatim_imports() {
    let output = namespace(
        r#"#' @import zebra
NULL
#' @import alpha, except = foo
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(alpha, except = foo)
    import(zebra)
    ");
}

#[test]
fn comma_bearing_import_is_independent_of_current_package() {
    let source = r#"#' @import current, except = foo
NULL
"#;
    let outputs = [
        ("none", namespace_with_package(source, None)),
        ("current", namespace_with_package(source, Some("current"))),
        ("external", namespace_with_package(source, Some("external"))),
    ];
    let baseline = &outputs[0].1;
    assert!(baseline.diagnostics.is_empty());
    insta::assert_snapshot!(baseline.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(current, except = foo)
    ");
    for (label, output) in &outputs[1..] {
        assert_eq!(
            output.content, baseline.content,
            "content changed for {label}"
        );
        assert_eq!(
            output.diagnostics, baseline.diagnostics,
            "diagnostics changed for {label}"
        );
    }
}

#[test]
fn typed_import_self_import_filtering_covers_both_decision_dimensions() {
    let cases = [
        ("no package, external", None, "external"),
        ("no package, current", None, "current"),
        ("package, external", Some("current"), "external"),
        ("package, current", Some("current"), "current"),
    ];
    let mut rendered = String::new();

    for (label, current_package, package) in cases {
        let source = format!(
            r#"#' @import {package}
NULL
#' @importFrom {package} self_name
NULL
"#
        );
        let output = namespace_with_package(&source, current_package);
        let codes = output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>();
        let is_self_import = current_package == Some("current") && package == "current";
        let expected_codes = if is_self_import {
            vec![DiagnosticCode::SelfImport, DiagnosticCode::SelfImport]
        } else {
            Vec::new()
        };
        assert_eq!(codes, expected_codes, "diagnostic codes for {label}");

        if is_self_import {
            let diagnostics = output.diagnostics.iter().collect::<Vec<_>>();
            assert_eq!(diagnostics[0].primary.span.range, TextRange::new(11, 18));
            assert_eq!(diagnostics[1].primary.span.range, TextRange::new(39, 46));
        }

        rendered.push_str(label);
        rendered.push('\n');
        rendered.push_str(&output.content);
    }

    insta::assert_snapshot!(rendered, @"
    no package, external
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(external)
    importFrom(external,self_name)
    no package, current
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(current)
    importFrom(current,self_name)
    package, external
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(external)
    importFrom(external,self_name)
    package, current
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand
    ");
}

#[test]
fn one_self_import_among_several_packages_does_not_take_the_others_with_it() {
    // The matrix above gives each case a single package, so it cannot see a
    // filter that stops at the first self-import instead of skipping only it.
    let output = namespace_with_package(
        r#"#' @import current external
NULL
"#,
        Some("current"),
    );
    let codes = output
        .diagnostics
        .iter()
        .map(|diagnostic| diagnostic.code)
        .collect::<Vec<_>>();
    assert_eq!(codes, vec![DiagnosticCode::SelfImport]);
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    import(external)
    ");
}

#[test]
fn import_from_is_merged_per_package_and_names_are_unique() {
    let output = namespace(
        r#"#' @importFrom utils tail head
NULL
#' @importFrom utils head
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(utils,
      head,
      tail
    )
    ");
}

#[test]
fn import_from_names_are_sorted_by_quoted_spelling() {
    let output = namespace(
        r#"#' @importFrom pkg A my-name
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(pkg,
      "my-name",
      A
    )
    "#);
}

#[test]
fn rendered_text_orders_all_namespace_directive_kinds_together() {
    let output = namespace(
        r#"#' @importFrom pkg A my-name
NULL
#' @import zebra
NULL
#' @import alpha, except = foo
NULL
#' @export a z-
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @r#"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export("z-")
    export(a)
    import(alpha, except = foo)
    import(zebra)
    importFrom(pkg,
      "my-name",
      A
    )
    "#);
}

#[test]
fn import_from_keeps_different_packages_separate() {
    let output = namespace(
        r#"#' @importFrom utils head
NULL
#' @importFrom stats median
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(stats,median)
    importFrom(utils,head)
    ");
}

#[test]
fn import_from_three_names_uses_compatibility_wrapping() {
    // This synthetic fixture pins the roxygen2 compatibility wrapping
    // convention; attribution is recorded in THIRD_PARTY_NOTICES.md.
    let output = namespace(
        r#"#' @importFrom fixture first_name second_name third_name
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    importFrom(fixture,
      first_name,
      second_name,
      third_name
    )
    ");
    // Inline snapshots normalize trailing whitespace, so the file ending in
    // exactly one newline has to be asserted on the bytes themselves.
    assert!(output.content.ends_with(")\n"));
    assert!(!output.content.ends_with(")\n\n"));
}

#[test]
fn duplicate_exports_collapse_and_order_is_input_independent() {
    let first = namespace(
        r#"#' @export
first <- function() NULL
#' @export
second <- function() NULL
"#,
    );
    let second = namespace(
        r#"#' @export
second <- function() NULL
#' @export
first <- function() NULL
"#,
    );
    assert_eq!(first.content, second.content);
    insta::assert_snapshot!(first.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(first)
    export(second)
    ");
}

#[test]
fn duplicate_exports_from_two_files_collapse_to_one_directive() {
    let mut sources = crate::source::SourceMap::new();
    let mut blocks = crate::model::test_support::blocks(
        &mut sources,
        "first.R",
        r#"#' @export
same <- function() NULL
"#,
    );
    blocks.extend(crate::model::test_support::blocks(
        &mut sources,
        "second.R",
        r#"#' @export
same <- function() NULL
"#,
    ));
    let package = crate::model::build_package_model(&sources, blocks).package;
    let output = build_namespace(&package, None);
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(same)
    ");
}

#[test]
fn invalid_directives_are_dropped_without_dropping_valid_directives() {
    let output = namespace(
        r#"#' @export
NULL
#' @import
NULL
#' @importFrom utils
NULL
#' @export too many
NULL
#' @import pkg extra
NULL
#' @export valid
NULL
"#,
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        3
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(many)
    export(too)
    export(valid)
    import(extra)
    import(pkg)
    ");
}

#[test]
fn extended_namespace_directives_reject_missing_arguments() {
    let output = namespace(
        r#"#' @importClassesFrom methods
NULL
#' @importMethodsFrom methods
NULL
"#,
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        2
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
}

#[test]
fn missing_class_or_method_names_beat_self_import_filtering() {
    let output = namespace_with_package(
        r#"#' @importClassesFrom current
NULL
#' @importMethodsFrom current
NULL
"#,
        Some("current"),
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![
            DiagnosticCode::InvalidNamespaceDirective,
            DiagnosticCode::InvalidNamespaceDirective
        ]
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
}

#[test]
fn use_dyn_lib_directives_preserve_argument_forms() {
    let output = namespace(
        r#"#' @useDynLib mypkg
NULL
#' @useDynLib mypkg routine_a routine_b
NULL
#' @useDynLib "mypkg" "routine_c"
NULL
#' @useDynLib mypkg, .registration = TRUE
NULL
"#,
    );
    assert!(output.diagnostics.is_empty());
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

useDynLib(mypkg)
useDynLib(mypkg, .registration = TRUE)
useDynLib(mypkg,routine_a)
useDynLib(mypkg,routine_b)
useDynLib(mypkg,routine_c)
"#);
}

#[test]
fn use_dyn_lib_rejects_undecodable_words() {
    let output = namespace(
        r#"#' @useDynLib "mypkg
NULL
"#,
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);

    let output = namespace(
        r#"#' @useDynLib mypkg "routine
NULL
"#,
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
}

#[test]
fn extended_namespace_directives_render_and_raw_namespace_stays_multiline() {
    let output = namespace(
        r#"#' @rawNamespace
#' if (TRUE) {
#'   importFrom(stats, median)
#' }
#' @exportPattern ^foo
#' @exportClass Foo
#' @exportMethod show
#' @importClassesFrom methods OldClass NewClass
#' @importMethodsFrom methods show
NULL
"#,
    );
    assert!(output.diagnostics.is_empty());
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand


if (TRUE) {
  importFrom(stats, median)
}
exportClasses(Foo)
exportMethods(show)
exportPattern("^foo")
importClassesFrom(methods,NewClass)
importClassesFrom(methods,OldClass)
importMethodsFrom(methods,show)
"#);
}

#[test]
fn raw_namespace_requires_parseable_r_source_and_accepts_multiple_expressions() {
    let invalid = namespace(
        r#"#' @rawNamespace a + b
NULL
"#,
    );
    assert_eq!(
        invalid
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(invalid.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);

    let unknown = namespace(
        r#"#' @rawNamespace unknownDirective(foo)
NULL
"#,
    );
    assert_eq!(
        unknown
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(unknown.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);

    let invalid_branch = namespace(
        r#"#' @rawNamespace if (TRUE) unknownDirective(foo)
NULL
"#,
    );
    assert_eq!(
        invalid_branch
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(invalid_branch.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);

    let invalid_name = namespace(
        r#"#' @rawNamespace _x <- 1
NULL
"#,
    );
    assert_eq!(
        invalid_name
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::InvalidNamespaceDirective]
    );
    insta::assert_snapshot!(invalid_name.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);

    let valid = namespace(concat!(
        r#"#' @rawNamespace
#' first <- export(first)"#,
        "\n#'   second <- import(pkg)\nNULL\n",
    ));
    assert!(valid.diagnostics.is_empty());
    insta::assert_snapshot!(valid.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand


first <- export(first)
  second <- import(pkg)
"#);
}

#[test]
fn export_class_rejects_more_than_one_name() {
    let output = namespace(
        r#"#' @exportClass Foo Bar
NULL
"#,
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::InvalidNamespaceDirective)
            .count(),
        1
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
}

#[test]
fn class_and_method_imports_skip_the_current_package_with_self_import_warnings() {
    let output = namespace_with_package(
        r#"#' @importClassesFrom current Class
NULL
#' @importMethodsFrom current method
NULL
"#,
        Some("current"),
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.code)
            .collect::<Vec<_>>(),
        vec![DiagnosticCode::SelfImport, DiagnosticCode::SelfImport]
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .map(|diagnostic| diagnostic.primary.span.range)
            .collect::<Vec<_>>(),
        vec![TextRange::new(22, 29), TextRange::new(63, 70)]
    );
    insta::assert_snapshot!(output.content, @r#"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

"#);
}

#[test]
fn no_rd_does_not_remove_namespace_exports() {
    let output = namespace(
        r#"#' @noRd
#' @export
hidden <- function() NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(hidden)
    ");
}

#[test]
fn end_to_end_namespace_contains_expected_mvp_directives() {
    let output = namespace(
        r#"#' @export
add <- function(x, y) x + y
#' @export
add3 <- function(x) x + 3
#' @importFrom utils head
#' @importFrom utils tail
NULL
"#,
    );
    insta::assert_snapshot!(output.content, @"
    # Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

    export(add)
    export(add3)
    importFrom(utils,
      head,
      tail
    )
    ");
}

#[test]
fn bare_export_infers_undocumented_late_and_nested_local_generics() {
    for (source, expected) in [
        (
            r#"generic <- function(x) UseMethod("different")
#' @export
generic.class <- function(x) x
"#,
            "generic",
        ),
        (
            r#"#' @export
late.class <- function(x) x
late <- function(x) UseMethod("another")
"#,
            "late",
        ),
        (
            r#"generic <- function(x) {
  identity(function() UseMethod("nested_name"))
}
#' @export
generic.class <- function(x) x
"#,
            "generic",
        ),
    ] {
        let output = namespace(source);
        assert!(output.diagnostics.is_empty(), "{source}");
        assert!(
            output
                .content
                .ends_with(&format!("S3method({expected},class)\n")),
            "{source}"
        );
    }

    let source = r#"generic <- function(x) {
  "UseMethod(\"generic\")"
  # UseMethod("generic")
  base::UseMethod("generic")
}
#' @export
generic.class <- function(x) x
"#;
    let output = namespace(source);
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n"
    );
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );
}

#[test]
fn local_aliases_resolve_across_files_and_explicit_one_word_exports() {
    let output = namespace_files(&[
        (
            "generic.R",
            "generic <- function(x) UseMethod(\"different\")\nhelper <- function(x) x\nhelper_alias <- helper\n",
        ),
        (
            "method.R",
            "generic_alias <- generic\n#' @export\ngeneric_alias.class <- helper_alias\n",
        ),
    ]);
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\nS3method(generic_alias,class)\n"
    );
    assert!(output.diagnostics.is_empty());

    for (generic, object) in [("head", "head.class"), ("tail", "tail.class")] {
        let source = format!(
            "impl <- function(x) x\n#' @exportS3Method utils::{generic}\n{object} <- impl\n"
        );
        let output = namespace(&source);
        assert_eq!(
            output.content,
            format!(
                "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\nS3method(utils::{generic},class)\n"
            )
        );
        assert!(output.diagnostics.is_empty());
    }
}

#[test]
fn aliases_respect_evaluation_order_and_collate_presence() {
    let cases = [
        (
            "same-file target before alias",
            vec![(
                "test.R",
                "generic <- function(x) UseMethod(\"generic\")\ngeneric_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
            )],
            false,
            true,
        ),
        (
            "same-file target after alias",
            vec![(
                "test.R",
                "generic_alias <- generic\ngeneric <- function(x) UseMethod(\"generic\")\n#' @export\ngeneric_alias.class <- function(x) x\n",
            )],
            false,
            false,
        ),
        (
            "cross-file target before alias",
            vec![
                (
                    "a-generic.R",
                    "generic <- function(x) UseMethod(\"generic\")\n",
                ),
                (
                    "b-method.R",
                    "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
                ),
            ],
            false,
            true,
        ),
        (
            "cross-file target after alias",
            vec![
                (
                    "a-method.R",
                    "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
                ),
                (
                    "b-generic.R",
                    "generic <- function(x) UseMethod(\"generic\")\n",
                ),
            ],
            false,
            false,
        ),
        (
            "cross-file target before alias with Collate",
            vec![
                (
                    "a-generic.R",
                    "generic <- function(x) UseMethod(\"generic\")\n",
                ),
                (
                    "b-method.R",
                    "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
                ),
            ],
            true,
            false,
        ),
        (
            "cross-file target after alias with Collate",
            vec![
                (
                    "a-method.R",
                    "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
                ),
                (
                    "b-generic.R",
                    "generic <- function(x) UseMethod(\"generic\")\n",
                ),
            ],
            true,
            false,
        ),
        (
            "same-file target before alias with Collate",
            vec![(
                "test.R",
                "generic <- function(x) UseMethod(\"generic\")\ngeneric_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
            )],
            true,
            true,
        ),
        (
            "same-file target after alias with Collate",
            vec![(
                "test.R",
                "generic_alias <- generic\ngeneric <- function(x) UseMethod(\"generic\")\n#' @export\ngeneric_alias.class <- function(x) x\n",
            )],
            true,
            false,
        ),
    ];

    for (name, files, collate, succeeds) in cases {
        let output = namespace_files_with_collate(&files, collate);
        assert_eq!(
            output.content.contains("S3method(generic_alias,class)"),
            succeeds,
            "{name}"
        );
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            usize::from(!succeeds),
            "{name}"
        );
    }
}

#[test]
fn cross_file_aliases_require_filename_evidence() {
    let reverse_registration = [
        (
            "b-method.R",
            "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
        ),
        (
            "a-generic.R",
            "generic <- function(x) UseMethod(\"generic\")\n",
        ),
    ];
    let (package, sources) = package_files_with_collate(&reverse_registration, false);
    let output = build_namespace_with_sources(&package, &sources, None);
    assert!(output.content.contains("S3method(generic_alias,class)"));

    let conservative = build_namespace(&package, None);
    assert!(
        !conservative
            .content
            .contains("S3method(generic_alias,class)")
    );
    assert_eq!(
        conservative
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );

    for files in [
        [
            (
                "a-method.R",
                "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
            ),
            (
                "b-generic.R",
                "generic <- function(x) UseMethod(\"generic\")\n",
            ),
        ],
        [
            (
                "one/generic.R",
                "generic <- function(x) UseMethod(\"generic\")\n",
            ),
            (
                "two/generic.R",
                "generic_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
            ),
        ],
    ] {
        let (package, sources) = package_files_with_collate(&files, false);
        let output = build_namespace_with_sources(&package, &sources, None);
        assert!(!output.content.contains("S3method(generic_alias,class)"));
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            1
        );
    }

    let (package, _) = package_files_with_collate(&reverse_registration, false);
    let output = build_namespace_with_sources(&package, &SourceMap::new(), None);
    assert!(!output.content.contains("S3method(generic_alias,class)"));
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );

    let (same_file, sources) = package_files_with_collate(
        &[(
            "same.R",
            "generic <- function(x) UseMethod(\"generic\")\ngeneric_alias <- generic\n#' @export\ngeneric_alias.class <- function(x) x\n",
        )],
        false,
    );
    let output = build_namespace(&same_file, None);
    assert!(output.content.contains("S3method(generic_alias,class)"));
    assert!(
        build_namespace_with_sources(&same_file, &sources, None)
            .content
            .contains("S3method(generic_alias,class)")
    );
}

#[test]
fn alias_edges_are_checked_for_each_hop_and_for_exported_object_functionness() {
    for (source, succeeds) in [
        (
            "generic <- function(x) UseMethod(\"generic\")\nalias1 <- generic\nalias2 <- alias1\n#' @export\nalias2.class <- function(x) x\n",
            true,
        ),
        (
            "alias2 <- alias1\nalias1 <- generic\ngeneric <- function(x) UseMethod(\"generic\")\n#' @export\nalias2.class <- function(x) x\n",
            false,
        ),
        (
            "alias <- identity\nidentity <- function(x) UseMethod(\"identity\")\n#' @export\nalias.class <- function(x) x\n",
            false,
        ),
    ] {
        let output = namespace(source);
        assert_eq!(output.content.contains("S3method("), succeeds, "{source}");
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            usize::from(!succeeds),
            "{source}"
        );
    }

    for source in [
        "generic <- function(x) UseMethod(\"generic\")\n#' @export\ngeneric.class <- later_function\nlater_function <- function(x) x\n",
        "generic <- function(x) UseMethod(\"generic\")\n#' @export\ngeneric.class <- later_value\nlater_value <- 1\n",
    ] {
        let output = namespace(source);
        assert!(
            !output.content.contains("export(generic.class)"),
            "{source}"
        );
        assert!(!output.content.contains("S3method("), "{source}");
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            1,
            "{source}"
        );
    }
}

#[test]
fn only_decoded_unqualified_use_method_identifiers_prove_generics() {
    for (callee, succeeds) in [
        ("UseMethod(\"generic\")", true),
        ("`UseMethod`(\"generic\")", true),
        ("base::UseMethod(\"generic\")", false),
        ("base:::UseMethod(\"generic\")", false),
        ("\"UseMethod\"(\"generic\")", false),
        ("`Use\\101Method`(\"generic\")", false),
    ] {
        let source = format!(
            "generic <- function(x) {{ {callee} }}\n#' @export\ngeneric.class <- function(x) x\n"
        );
        let output = namespace(&source);
        assert_eq!(
            output.content.contains("S3method(generic,class)"),
            succeeds,
            "{callee}"
        );
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            usize::from(!succeeds),
            "{callee}"
        );
    }
}

#[test]
fn super_assignments_and_walrus_do_not_establish_package_bindings() {
    for source in [
        "supergen <<- function(x, ...) UseMethod(\"supergen\")\n#' @export\nsupergen.foo <- function(x, ...) x\n",
        "function(x, ...) UseMethod(\"supergen\") ->> supergen\n#' @export\nsupergen.foo <- function(x, ...) x\n",
        "supergen := function(x, ...) UseMethod(\"supergen\")\n#' @export\nsupergen.foo <- function(x, ...) x\n",
    ] {
        let output = namespace(source);
        assert!(!output.content.contains("S3method("), "{source}");
        assert!(!output.content.contains("export(supergen.foo)"), "{source}");
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            1,
            "{source}"
        );
    }

    let output = namespace(
        "supergen <- function(x, ...) UseMethod(\"supergen\")\nsupergen <<- function(x, ...) x\n#' @export\nsupergen.foo <- function(x, ...) x\n",
    );
    assert!(output.content.contains("S3method(supergen,foo)"));
    assert!(output.diagnostics.is_empty());
}

#[test]
fn split_selection_is_first_prefix_with_all_equal_special_case() {
    let output = namespace(
        r#"foo <- function(x) UseMethod("foo")
foo.bar <- function(x) UseMethod("foo.bar")
#' @export
foo.bar.baz <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(foo,bar.baz)
");
    assert!(output.diagnostics.is_empty());

    let output = namespace(
        r#"foo.bar <- function(x) UseMethod("foo.bar")
#' @export
foo.bar.baz <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(foo.bar,baz)
");
    assert!(output.diagnostics.is_empty());

    let output = namespace(
        r#"generic <- function(x) UseMethod("generic")
#' @export
generic. <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

");
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );

    let output = namespace(
        r#"generic <- function(x) UseMethod("generic")
#' @export
generic..kind <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(generic,.kind)
");
    assert!(output.diagnostics.is_empty());

    for generic_definitions in [
        "all <- function(x) UseMethod(\"all\")\nall.equal <- function(x) UseMethod(\"all.equal\")\n",
        "all <- function(x) UseMethod(\"all\")\n",
    ] {
        let source = format!("{generic_definitions}#' @export\nall.equal.foo <- function(x) x\n");
        let output = namespace(&source);
        if generic_definitions.contains("all.equal") {
            insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(all.equal,foo)
");
        } else {
            insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(all,equal.foo)
");
        }
        assert!(output.diagnostics.is_empty());
    }
}

#[test]
fn multi_dot_s3_methods_choose_the_shortest_proven_generic_prefix() {
    let output = namespace(
        r#"alpha <- function(x) UseMethod("alpha")
alpha.beta <- function(x) UseMethod("alpha.beta")
#' @export
alpha.beta.gamma.delta <- function(x) x
"#,
    );
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(alpha,beta.gamma.delta)
");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn multi_dot_provider_generics_remain_shadowed_by_local_bindings() {
    let model = model(
        r#"alpha <- function(x) x
alpha.beta <- 1
#' @export
alpha.beta.gamma.kind <- function(x) x
"#,
    );
    let provider = FakeGenericProvider(BTreeSet::from(["alpha.beta".to_owned()]));
    let output = build_namespace_with_provider(&model.package, None, &provider);
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

");
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );
}

#[test]
fn multi_dot_provider_generics_supply_the_selected_prefix() {
    let model = model(
        r#"#' @export
alpha.beta.gamma.kind <- function(x) x
"#,
    );
    let provider = FakeGenericProvider(BTreeSet::from(["alpha.beta".to_owned()]));
    let output = build_namespace_with_provider(&model.package, None, &provider);
    insta::assert_snapshot!(output.content, @r"
# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand

S3method(alpha.beta,gamma.kind)
");
    assert!(output.diagnostics.is_empty());
}

#[test]
fn unknown_aliases_cycles_competing_assignments_and_calls_are_refused() {
    for source in [
        "#' @export\nmissing.class <- missing\n",
        r#"#' @export
undecodable.class <- `missing\name`
"#,
        "cycle <- cycle2\ncycle2 <- cycle\n#' @export\ncycle.class <- cycle\n",
        "comp.class <- function(x) x\ncomp.class <- function(x) x\n#' @export\ncomp.class <- function(x) x\n",
        "#' @export\ncall.class <- make_function()\n",
    ] {
        let output = namespace(source);
        assert_eq!(
            output.content,
            "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n",
            "{source}"
        );
        assert_eq!(
            output
                .diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
                .count(),
            1,
            "{source}"
        );
    }
}

#[test]
fn non_functions_are_ordinary_exports_but_explicit_and_worded_exports_bypass_inference() {
    let output = namespace(
        r#"#' @export
value.class <- 1
#' @export
plain.class <- function(x) x
#' @method explicit class
#' @export
explicit.class <- function(x) x
#' @export named
worded.class <- function(x) x
"#,
    );
    assert!(output.content.contains("export(value.class)"));
    assert!(output.content.contains("S3method(explicit,class)"));
    assert!(output.content.contains("export(named)"));
    assert!(!output.content.contains("export(plain.class)"));
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );
}

#[test]
fn inferred_operator_replacement_and_backticked_names_use_auto_quoting() {
    let output = namespace(
        r#"`+` <- function(x, y) UseMethod("different")
#' @export
`+.class.with.dots` <- function(x, y) x
`foo<-` <- function(x, value) UseMethod("different")
#' @export
`foo<-.class` <- function(x, value) x
"#,
    );
    assert!(output.content.contains("S3method(\"+\",class.with.dots)"));
    assert!(output.content.contains("S3method(\"foo<-\",class)"));
    assert!(output.diagnostics.is_empty());
}

#[test]
fn unresolved_s3_warning_has_exact_contract_and_binding_span() {
    let output = namespace(
        r#"#' @export
`unknown.class` <- function(x) x
"#,
    );
    let diagnostic = output
        .diagnostics
        .iter()
        .find(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
        .expect("unresolved S3 warning");
    assert_eq!(diagnostic.severity, Severity::Warning);
    assert_eq!(diagnostic.code.as_str(), "unresolved-s3-export");
    assert_eq!(
        diagnostic.message,
        "cannot distinguish unknown.class as an S3 method from a plain dotted function without evaluating R"
    );
    assert_eq!(
        diagnostic.help.as_deref(),
        Some(
            "add @method <generic> <class> before the bare @export, or replace it with @exportS3Method <generic> <class>"
        )
    );
    assert_eq!(
        diagnostic.primary.message,
        "automatic S3 classification is unresolved"
    );
    assert_eq!(diagnostic.primary.span.range, TextRange::new(11, 26));
    assert_eq!(
        output
            .diagnostics
            .iter()
            .filter(|diagnostic| diagnostic.code == DiagnosticCode::UnresolvedS3Export)
            .count(),
        1
    );
    assert_eq!(
        output.content,
        "# Generated by mini-roxygen (roxygen2 compatible): do not edit by hand\n\n"
    );
}
